# Generated by Django 2.2.18 on 2022-02-10 09:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('organization_id', models.AutoField(primary_key=True, serialize=False)),
                ('organization_name', models.CharField(max_length=200)),
                ('organization_short_name', models.CharField(default='', max_length=200)),
            ],
            options={
                'verbose_name_plural': '1. Organization',
            },
        ),
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=10000, verbose_name='Project name')),
                ('project_note', models.TextField(blank=True, default='')),
                ('organization', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='projects.Organization')),
            ],
            options={
                'verbose_name_plural': '2. Projects',
            },
        ),
        migrations.CreateModel(
            name='Targets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_name', models.TextField(blank=True, default='')),
                ('target_status', models.IntegerField(choices=[(1, 'CREATED'), (2, 'SCANNING'), (3, 'DONE')], default=1)),
                ('target_source_code', models.FileField(default=None, upload_to='documents/%Y/%m/%d/')),
                ('target_scan_options_json', models.TextField(blank=True, default='{"language":["python","java"],"scan_type":"full_scan"}', null=True)),
                ('target_scan_notification_config_json', models.TextField(blank=True, default='{}', null=True)),
                ('project', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='projects.Projects')),
            ],
            options={
                'verbose_name_plural': '3. Targets',
            },
        ),
        migrations.CreateModel(
            name='Scans',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(auto_now_add=True, verbose_name='Finished time')),
                ('finished_time', models.DateTimeField(auto_now_add=True, verbose_name='Finished time')),
                ('scan_result_json', models.TextField(blank=True, null=True)),
                ('scan_status', models.IntegerField(choices=[(1, 'CREATED'), (2, 'SCANNING'), (3, 'DONE')], default=1)),
                ('scan_options_json', models.TextField(blank=True, default='{"language":["python","java"],"scan_type":"full_scan"}', editable=False, null=True)),
                ('scan_notification_config_json', models.TextField(blank=True, default='{}', null=True)),
                ('target', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='projects.Targets')),
            ],
            options={
                'verbose_name_plural': '4. Scans',
            },
        ),
    ]
