# Generated by Django 3.2.12 on 2022-02-18 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_auto_20220214_0408'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scans',
            name='finished_time',
        ),
    ]
