# Generated by Django 3.2.12 on 2022-02-18 06:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_remove_scans_finished_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='scans',
            name='finished_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Finished time'),
            preserve_default=False,
        ),
    ]
